name: stacer
adopt-info: stacer
title: Stacer
base: core24
summary: Linux System Optimizer and Monitoring
description: |
  Stacer is an open source system optimizer and application monitor that helps users to manage entire system with different aspects, its an all in one system utility.
license: GPL-3.0
icon: icons/hicolor/scalable/apps/stacer.svg

website: https://stacer.quentium.fr
contact: pro@quentium.fr
source-code: https://github.com/QuentiumYT/Stacer
issues: https://github.com/QuentiumYT/Stacer/issues
donation: https://www.paypal.me/QuentiumYT

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]
  riscv64:
    build-on: [riscv64]
    build-for: [riscv64]
  s390x:
    build-on: [s390x]
    build-for: [s390x]

apps:
  stacer:
    command: usr/bin/stacer
    extensions: [kde-neon-6]
    plugs:
      - network
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - opengl
      # manual plugs
      - hardware-observe
      - network-observe
      - system-observe
      - process-control
      - removable-media
      # custom stacer plugs
      - dot-config-autostart
      - dot-cache-clean
      - dot-config-clean
      - local-trash-clean
      - var-crash-clean
      - var-log-clean
      - var-cache-apt-clean
      - apt-config

plugs:
  dot-config-autostart:
    interface: personal-files
    write:
      - $HOME/.config/autostart
  dot-cache-clean:
    interface: personal-files
    write:
      - $HOME/.cache
  dot-config-clean:
    interface: personal-files
    write:
      - $HOME/.config
  local-trash-clean:
    interface: personal-files
    write:
      - $HOME/.local/share/Trash
  var-crash-clean:
    interface: system-files
    write:
      - /var/crash
  var-log-clean:
    interface: system-files
    write:
      - /var/log
  var-cache-apt-clean:
    interface: system-files
    write:
      - /var/cache/apt/archives
  apt-config:
    interface: system-files
    write:
      - /etc/apt/sources.list
      - /etc/apt/sources.list.d

parts:
  stacer:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-snaps:
      - kde-qt6-core24-sdk
    build-packages:
      - git
      - build-essential
      - cmake
      - pkg-config
      - libglx-dev
      - libxkbcommon-dev
      - libvulkan-dev
    stage-packages:
      - libc6
      - systemd
      - curl
    build-attributes:
      - enable-patchelf
    override-pull: |
      craftctl default
      VERSION="$(git describe --tags --abbrev=0)"
      craftctl set version=$VERSION
      git checkout snapcraft
